language: python

dist: bionic

python:
  - "3.8"
  - "3.7"
  - "3.6"

env:
  # boto config is dirty on some travis images
  # https://github.com/travis-ci/travis-ci/issues/7940
  - BOTO_CONFIG=/dev/null

services:
  - mysql

branches:
  only:
    - master
    # build release tags
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - pip install cython

install:
  - pip install -e .[test]

before_script:
  - pip freeze

script:
  - python -m pytest --color=yes --cov=terracotta --mysql-server="root@127.0.0.1"
  - python -m pytest --color=yes tests/benchmarks.py

after_success:
  - codecov

notifications:
  email: false

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "lGexaFNOHer0sfvwc8rIDbOZuxb90G+v5hIjrrqroHFfk6TPsC83ACCtfT1TyglP1FT0guw29n9BecqWLa0mD0ZH/PPBM2zoYEoUz9YFDuFGnf5XaKUKy8ZJH71E44BntblfVWpU9kZsAZTrtyHOXFqdKjcRoA9J6hvEAJWPUHvoyjN9rkK6ayBqFiKDVI1FDC3ir27FoC75JoE1JixI+CbSLzqbguk7ttSqZP5Tg8FYyxUMf7esoB+fxvy0+me55H5jZUj6jlHxbQ0uqO1jDhgnRKU4NMJuLD6BI9aRSHXhwXpPKVFDvQKgIIAPvf6GMXZkuEK71dJhDjuyEH9uj1isgfGjSOQHg6PnojcOZZCTDrV1i1z4YeC960QCwuAF9iqrGGxaMknUMT78R9f0vsGn46P+L/evy3gMsWsAg7utf5u2HmPmU6H5mO8FXpaf4qbfDNxM7uDVi3vwoovTRIRO/3mVm6o+Mh5+ab6FEuQ7S40kL1xel5iLW8QQUtv/LCW0aQtct+Q0EDlalCPl2qqZm8BKPaoqrPwfH+F+WIhgeqqVCVaJm66VUoyjW390e762xQMjk+0jnXYtdQ9SPtZNWTqewycCnrqsv4D4iHcAk15BsV5m5FbayUANNjdFVfjLpzIDqWWDQq6caDPu1pdYYxLqEwQzT54TkThH0gg="
  on:
    tags: true
  skip_existing: true
